spring.application.name=demo
server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/Foodly
spring.datasource.username=postgres
spring.datasource.password=beniteBe0
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

security.jwt.secret=${JWT_SECRET:change-this-secret-key-change-this-secret-key-123456}
security.jwt.expiration-ms=${JWT_EXPIRATION_MS:900000}
